### PR TITLE
Switch default to llvm13

### PR DESCRIPTION
**Pull request by fgsch**

### CODE REVIEW

**Review by aykevl — COMMENTED** [review]
The files llvm_config_darwin.go and llvm_config_linux.go still point to the older versions. Perhaps they can be renamed to add the version suffix?
(Previously I would make sure those files were always the default version, but maybe that makes things unnecessarily complicated).

Other than that, looks good to me.

**Comment by fgsch** [comment]
Maybe we should simply rename those to include the llvm version and stop renaming it to avoid unnecessary churn?

**Comment by aykevl** [comment]
Yes, that's what I meant.

**Comment by fgsch** [comment]
Doh, of course, I misread it.. Updated.

**Review by aykevl — APPROVED** [review]

**Comment by aykevl** [comment]
Thank you!

**Comment by deadprogram** [comment]
Do we need to update the modules in the main TinyGo repo again now?

**Comment by aykevl** [comment]
Yes, and also the cgo/libclang_config*.go files.

**Comment by fgsch** [comment]
https://github.com/tinygo-org/tinygo/pull/2567

**Pull request merged**
