### PR TITLE
Update Darwin to LLVM11

### PR DESCRIPTION
**Pull request by kenbell**
This brings Darwin inline with Linux, which is LLVM11 by default

LLVM11 is now the default in homebrew.

### CODE REVIEW

**Comment by kenbell** [comment]
@aykevl @deadprogram - any chance of getting this merged?

**Comment by aykevl** [comment]
Did you test this change (using `go install`)? with LLVM 11? You can test it using a `replace` line: https://golang.org/ref/mod#go-mod-edit

**Comment by kenbell** [comment]
Yep - I've done a 'go install', it's what I'm currently using since updating homebrew.

There's another bug preventing building llvm from source to build tinygo (see https://github.com/tinygo-org/tinygo/issues/1573), so this is the only way I've found to compile tinygo on Mac right now.

**Comment by aykevl** [comment]
Okay, thank you for confirming!

**Pull request merged**
