### PR TITLE
Add new pass manager API

### PR DESCRIPTION
**Pull request by rj45**
Just in case you want this code, I implemented the new pass manager. Looks like soon this will be the only pass manager API available as they will be removing the old APIs.

This API looks like it's been available since LLVM 14 or earlier, so I think it should be safe.

I added a test.... it's mostly copy pasta from another test, but hey it's better than nothing, and it checks that the error handling code is correct.

Let me know if you're interested in these PRs. If you're not, I can just maintain my own fork. I understand you not wanting to maintain code that is not depended upon by tinygo. Though, in this case, I think you might want this code as it will be required eventually.

Feel free to close this PR and go a different direction, or make any edits you would like, I don't mind.

### CODE REVIEW

**Comment by rj45** [comment]
Accidentally put the CI fix on the wrong branch. Let me know if I should instead force push without the commits.

**Review by aykevl — COMMENTED** [review]
Looks reasonable to me. I'll test this with TinyGo to see whether the API also works there.

One possible improvement is to add more documentation comments. Most functions in the go-llvm API don't have that, but that's no reason to not add them for new APIs (the go-llvm package API is generally not exactly the best API design, to put it mildly).

**Comment by aykevl** [comment]
> Let me know if I should instead force push without the commits.

I generally prefer to have a clean git history, so if you can remove the last two commits that would be great.

**Comment by aykevl** [comment]
Tested this API with TinyGo and it works well.

Can you do the following to make this PR mergeable?
* Rebase on the master branch.
* Remove the last two commits (optional, but preferred).
* Update the tests to avoid the global context (https://github.com/tinygo-org/go-llvm/pull/50#discussion_r1329999491)
* Optional: improve the doc comments for the new methods.

**Comment by rj45** [comment]
@aykevl Done. I had to do some investigation to figure out what some of the options actually do, one or two I had to kind of extrapolate what it might do based on what little scraps of comments I could find on the option. Like forgetting the scalar evolution -- I am guessing that could prevent loop unrolling in some cases, but I couldn't find anything that said that, so I just said "it could affect loop unrolling in some cases". 

Let me know if I missed anything when converting the test not to use the global context. I just assumed you removed all of the global context functions, so if the test passed I got them all.

**Comment by aykevl** [comment]
Looks good to me, thank you for the update!

> Let me know if I missed anything when converting the test not to use the global context. I just assumed you removed all of the global context functions, so if the test passed I got them all.

I hope I found all of them! At least I tried to.

**Pull request merged**
