### PR TITLE
Add support for LLVM 13

### PR DESCRIPTION
**Pull request by QuLogic**
~~This is based on #21.~~

The second-last commit is perhaps something that should go to the Go bindings in LLVM, but I'm not sure if they'd want to just drop those attributes, or actually write tests for them.

### CODE REVIEW

**Comment by aykevl** [comment]
Thank you for your work on this!
Can you rebase this on the master branch and add CI testing (see .github/workflows/test.yml)? I've added GitHub Actions just now to make sure PRs on this repo actually work.

**Comment by QuLogic** [comment]
> I've added GitHub Actions just now to make sure PRs on this repo actually work.

:+1: They're run on push and not pull requests, though, so here's the link to the build on the latest commit: https://github.com/QuLogic/go-llvm/actions/runs/1635636703

**Review by aykevl — APPROVED** [review]
LGTM, thanks!

**Comment by aykevl** [comment]
> +1 They're run on push and not pull requests, though

Hmm, then GHA didn't work exactly as I expected. Feel free to send a PR if you want :)

**Pull request merged**
